### ISSUE TITLE
Custom Ambient sense?

### ISSUE THREAD

**Issue by frap129** [denysvitali/magisk-pixel2-features#3]
Hey, just wondering, what all did you change in your custom ambient sense apk? I have all of the SystemUI changes reverse engineered from SystemUIGoogle, but the settings menu is not showing up on devices that arent pixel.

**Comment by denysvitali** [comment]
The only change that was made to the Ambient Sense APK was to expose some intents in such a way that they could be started w/ `adb shell su -c 'am start com.google.intelligence.sense/com.google.intelligence.sense.ambientmusic.AmbientMusicSetupWizard' `.  
If you have a Nexus - Pixel phone the menu will show up in the settings. For any other device you'll need to use the `am start` command.

**Comment by frap129** [comment]
Did you see any code that would prevent non-pixel devices from using the service? I've got the settings menu working on all devices (had to whitelist it from battery optimizations) but it never actually listens for music

**Comment by dj1818** [comment]
Oneplus 5 with stock rom (8.0), latest magisk.
```
D:\Nexus>adb shell su -c 'am start com.google.intelligence.sense/com.google.intelligence.sense.ambientmusic.AmbientMusicSetupWizardActivity'
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.google.intelligence.sense/.ambientmusic.AmbientMusicSetupWizardActivity }
Error type 3
Error: Activity class {com.google.intelligence.sense/com.google.intelligence.sense.ambientmusic.AmbientMusicSetupWizardActivity} does not exist.

D:\Nexus>adb shell su -c 'am start com.google.intelligence.sense/com.google.intelligence.sense.ambientmusic.AmbientMusicSettingsActivity'
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.google.intelligence.sense/.ambientmusic.AmbientMusicSettingsActivity }
Error type 3
Error: Activity class {com.google.intelligence.sense/com.google.intelligence.sense.ambientmusic.AmbientMusicSettingsActivity} does not exist.
```
and so don't work, even with given permission for mic.

**Comment by denysvitali** [comment]
You should probably update the Ambient Sense app from the Play Store. Please mind that currently the Ambient Sense feature doesn't work yet.

**Comment by frap129** [comment]
@denysvitali From what I've found, whitelisting the Ambient Sense app from power optimizations makes the menu appear in settings on non-nexus/pixel devices, however, it seems to be locked down on other devices. Do you you know if it works on Nexus 6P/5X and Pixel 1 devices? I'm still researching how the app blocks non-nexus/pixel devices.

**Comment by denysvitali** [comment]
I've got that menu on a Nexus 6P by using the latest Android build (8.1) and applying this module.  
Unfortunately I haven't found a way to make it work (to recognize the songs) on any device I tested so far (Oneplus One, Oneplus 5T, Nexus 6P, Pixel C)

**Comment by frap129** [comment]
Ahh, ok. I was looking through the source and found an array of device names that included marlin, sailfish, angler, and bullhead, and thought that it may work on those. Just a fair warning (that you probably know already), SystemUI requires modification for it to show on the lockscreen, but notifications dont, so make sure thats enabled.

**Comment by denysvitali** [comment]
Tbh my goal was to achieve the notification feature first, then work on the lockscreen (which as you said requires a modification on the System UI, precisely on the Ambient Display).  
At the moment neither the notifications nor the Lockscreen displays anything about the song being recognized
